"""
Telegram polling glue for the Supermarket Ops Agent.

Text messages are routed to Gemini/Google ADK.
Generated PDF/PPTX artifacts are sent back as Telegram documents.
"""

from pathlib import Path

from aiogram import Bot, Dispatcher
from aiogram.filters import Command
from aiogram.types import FSInputFile, Message

from bot import config
from bot.agent import (
    consume_generated_files,
    handle_message,
    reset_session,
)


dp = Dispatcher()


@dp.message(Command("new"))
async def cmd_new(message: Message) -> None:
    await reset_session(str(message.chat.id))

    await message.answer(
        "Started a fresh conversation. "
        "Stock, bills, khata and preferences are unchanged."
    )


@dp.message()
async def on_message(message: Message) -> None:
    if not message.text:
        await message.answer(
            "I can only read text messages right now."
        )
        return

    chat_id = str(message.chat.id)
    message_key = f"{chat_id}:{message.message_id}"

    try:
        reply = await handle_message(
            chat_id,
            message.text,
            message_key,
        )

        await message.answer(reply)

        # Send any PDF/PPTX generated by the agent.
        generated_files = consume_generated_files(chat_id)

        for file_path in generated_files:
            path = Path(file_path)

            if not path.exists():
                await message.answer(
                    f"The document was generated, but I couldn't "
                    f"find the file: {path.name}"
                )
                continue

            await message.answer_document(
                FSInputFile(
                    path,
                    filename=path.name,
                )
            )

    except Exception as exc:
        await message.answer(
            f"Sorry, something went wrong: {exc}"
        )


def run_bot() -> None:
    if not config.TELEGRAM_BOT_TOKEN:
        raise RuntimeError(
            "TELEGRAM_BOT_TOKEN is not set. "
            "Add it to .env."
        )

    import asyncio

    bot = Bot(
        token=config.TELEGRAM_BOT_TOKEN,
    )

    asyncio.run(
        dp.start_polling(bot)
    )